---
#reduced_heat_exchange: 30
actuators:
  pump:
    dev: "relay"
    circuit: "3"
  switch:
    dev: "relay"
    circuit: "2"
  flow:
    dev: "ao"
    circuit: "1"
sensors:
  solarUp:
    dev: "ai"
    circuit: "1"
  solarIn:
    dev: "temp"
    circuit: "28FFABCDEFFEDCBA"
  solarOut:
    dev: "temp"
    circuit: "28FFABCDEFFEDCBA"
  tankUp:
    dev: "temp"
    circuit: "28FFABCDEFFEDCBA"
settings:
  solarCritical:
    address: "solar/settings/critical"
    value: 90
  solarOn:
    address: "solar/settings/on"
    value: 8
  solarOff:
    address: "solar/settings/off"
    value: 5
  tankMax:
    address: "solar/settings/tank"
    value: 65
  flow:
    tempMin:
      address: "solar/settings/flow/t_min"
      value: 5
    tempMax:
      address: "solar/settings/flow/t_max"
      value: 9
    dutyMin:
      address: "solar/settings/flow/d_min"
      value: 1.8
    dutyMax:
      address: "solar/settings/flow/d_max"
      value: 3
