---
#reduced_heat_exchange: 30
actuators:
  pump:
    dev: "relay"
    circuit: "3"
  switch:
    dev: "relay"
    circuit: "2"
  flow:
    dev: "ao"
    circuit: "1"
sensors:
  solarUp:
    dev: "ai"
    circuit: "1"
  solarIn:
    dev: "temp"
    circuit: "28FFABCDEFFEDCBA"
  solarOut:
    dev: "temp"
    circuit: "28FFABCDEFFEDCBA"
  tankUp:
    dev: "temp"
    circuit: "28FFABCDEFFEDCBA"
settings:
  solarEmergency:
    entity_id: "input_boolean.solar_emergency_shutoff"
  solarCritical:
    entity_id: "input_number.solar_critical"
  solarOn:
    entity_id: "input_number.solar_diff_on"
  solarOff:
    entity_id: "input_number.solar_diff_off"
  tankMax:
    entity_id: "input_number.solar_tank_max"
  flow:
    tempMin:
      entity_id: "input_number.solar_flow_temp_min"
    tempMax:
      entity_id: "input_number.solar_flow_temp_max"
    dutyMin:
      entity_id: "input_number.solar_flow_duty_min"
    dutyMax:
      entity_id: "input_number.solar_flow_duty_max"
