---
actuators:
  pump: "testing/solar/actuators/pump"
  switch: "testing/solar/actuators/switch"
  flow: "testing/solar/actuators/flow"
sensors:
  solarIn:
    address: "solar/temperature/in"
  solarOut:
    address: "solar/temperature/out"
  solarUp:
    address: "solar/temperature/up"
  tankUp:
    address: "tank/temperature/up"
settings:
  solarCritical:
    address: "solar/settings/critical"
    value: 90
  solarOn:
    address: "solar/settings/on"
    value: 8
  solarOff:
    address: "solar/settings/off"
    value: 5
  tankMax:
    address: "solar/settings/tank"
    value: 65
  flow:
    tempMin:
      address: "solar/settings/flow/t_min"
      value: 5
    tempMax:
      address: "solar/settings/flow/t_max"
      value: 9
    dutyMin:
      address: "solar/settings/flow/d_min"
      value: 1.8
    dutyMax:
      address: "solar/settings/flow/d_max"
      value: 3
