name: goreleaser

on:
  push:
    branches: [master, main]
    tags: ['*']
  pull_request:
    branches: ['**']

env:
  golang-version: 1.18.0
  goreleaser-version: v1.7.0

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3.0.0
        with:
          go-version: ${{ env.golang-version }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        #login only on tags. Note that login can't work on PRs from forked repos because of missing secrets
        #this gets around that by only logging in when needed.
        if: startsWith(github.ref, 'refs/tags/')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run GoReleaser Test
        uses: goreleaser/goreleaser-action@v2
        # do not run test if actually releasing
        if: startsWith(github.ref, 'refs/tags/') != true
        with:
          distribution: goreleaser
          version: ${{ env.goreleaser-version }}
          args: release --snapshot --skip-publish --rm-dist -f .goreleaser.yml

      - name: GoReleaser Release
        uses: goreleaser/goreleaser-action@v2
        #release only on tags
        if: startsWith(github.ref, 'refs/tags/')
        with:
          distribution: goreleaser
          version: ${{ env.goreleaser-version }}
          args: release --rm-dist -f .goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}